Repository Central-MakeUs/CheatKey-Front, pull requests merged in 2025-07, with the labels that each got.

#7 [FEAT]: 커뮤니티 피드 UI 구현
  native/app/index.tsx
  web/eslint.config.js
  web/index.html
  web/package-lock.json
  web/package.json
  web/src/assets/icons/ai_analysis.svg
  web/src/assets/icons/arrow_up.svg
  web/src/assets/icons/comment.svg
  web/src/assets/icons/community.svg
  web/src/assets/icons/community_focused.svg
  web/src/assets/icons/community_post_menu.svg
  web/src/assets/icons/contents.svg
  web/src/assets/icons/contents_focused.svg
  web/src/assets/icons/dropdown.svg
  web/src/assets/icons/ellipse.svg
  web/src/assets/icons/home.svg
  web/src/assets/icons/home_focused.svg
  web/src/assets/icons/my.svg
  web/src/assets/icons/my_focused.svg
  web/src/assets/icons/search.svg
  web/src/assets/icons/temporary_profile_pic.png
  web/src/assets/images/community_test_image_1.jpg
  web/src/assets/images/community_test_image_2.jpg
  web/src/assets/images/community_test_image_3.jpg
  web/src/components/common/AppHeader.tsx
  web/src/components/common/BottomNavBar.tsx
  web/src/components/common/BottomNavBarItem.tsx
  web/src/components/common/SearchBar.tsx
  web/src/components/common/ToTop.tsx
  web/src/components/communityFeed/CommunityFeedScamTypeDropdown.tsx
  web/src/components/communityFeed/CommunityFeedTab.tsx
  web/src/components/communityFeed/CommunityPostPreview.tsx
  web/src/components/dummy.ts
  web/src/layout/BottomLayout.tsx
  web/src/mocks/mockCommunityFeedPreviews.ts
  web/src/pages/communityDetail/CommunityDetail.tsx
  web/src/pages/communityFeed/CommunityFeed.tsx
  web/src/pages/communityWrite/CommunityWrite.tsx
  web/src/pages/index.ts
  web/src/routes/AppRouter.tsx
  web/src/routes/path.ts
  web/src/styles/theme.css
  web/src/utils/throttle.ts
Labels: ✨ Feature, 🎨 Design

#10 [FEAT]: 사용자 액션을 요구하는 모달 컴포넌트 구현
  web/src/components/common/ConfirmModal.tsx
  web/src/styles/typography.css
Labels: ✨ Feature, 🎨 Design

#14 [CHORE]: 패키지 수정
  web/package-lock.json
  web/package.json
Labels: ⚙️ Chore

#11 [FEAT] 이용약관 UI 구현, 바텀 시트 컴포넌트 구현, 카카오 로그인 방식 변경
  web/index.html
  web/src/apis/auth/getAuthRegister.api.ts
  web/src/apis/axios-instance.ts
  web/src/assets/icons/checkbox_off.svg
  web/src/assets/icons/checkbox_on.svg
  web/src/components/common/BottomSheet.tsx
  web/src/components/login/KakaoLogin.tsx
  web/src/components/signup/NicknameForm.tsx
  web/src/components/signup/TermBottomSheet.tsx
  web/src/components/signup/TermForm.tsx
  web/src/constants/apiConstants.ts
  web/src/constants/termContents.ts
  web/src/pages/auth/SignUpPage.tsx
  web/src/styles/style.css
  web/src/types/signup/signup.types.ts
  web/vite.config.ts
Labels: ✨ Feature, 🎨 Design

#21 [FEAT]: 검색 페이지 UI 구현
  native/app/index.tsx
  native/components/dummy.ts
  web/src/assets/icons/erase.svg
  web/src/assets/images/cutting_sad.svg
  web/src/components/common/NameTag.tsx
  web/src/components/common/SearchBar.tsx
  web/src/components/common/SearchBarRedirect.tsx
  web/src/components/common/ToTop.tsx
  web/src/components/communityFeed/CommunityFeedSortOptionDropdown.tsx
  web/src/components/communityFeed/CommunityPostPreview.tsx
  web/src/components/searchPage/SearchResultPreview.tsx
  web/src/hooks/dummy.ts
  web/src/pages/communityFeed/CommunityFeed.tsx
  web/src/pages/home/Home.tsx
  web/src/pages/index.ts
  web/src/pages/searchPage/SearchPage.tsx
  web/src/routes/AppRouter.tsx
  web/src/routes/path.ts
  web/src/utils/dummy.ts
Labels: ✨ Feature, 🎨 Design

#24 [FEAT]: 커뮤니티 게시글 옵션 컴포넌트 UI 구현
  web/src/assets/icons/arrow_right.svg
  web/src/components/common/BottomFullButton.tsx
  web/src/components/common/ConfirmModal.tsx
  web/src/components/common/PostMenuButton.tsx
  web/src/components/common/ReportPostSheet.tsx
  web/src/components/communityFeed/CommunityPostPreview.tsx
  web/src/constants/reportReasons.ts
  web/src/styles/typography.css
Labels: ✨ Feature, 🎨 Design

#22 [FEAT]: 브릿지 설정 + 카카오 로그인 방식 변경 ( Web -> Native )
  native/.gitignore
  native/apis/axios-instance.ts
  native/apis/postSocialLogin.ts
  native/app.config.js
  native/app.json
  native/app/index.tsx
  native/bridge/index.ts
  native/package-lock.json
  native/package.json
  native/services/authStorage.ts
  native/social/performKakaoLogin.ts
  web/index.html
  web/package-lock.json
  web/package.json
  web/src/bridge/index.ts
  web/src/components/login/KakaoLogin.tsx
  web/src/constants/apiConstants.ts
  web/src/pages/auth/SignUpPage.tsx
  web/src/types/bridge/bridge.types.ts
Labels: ✨ Feature

#29 [FIX]: 웹 브릿지 타입 오류 수정
  web/src/types/bridge/bridge.types.ts
Labels: 🐞 Bug

#33 [FEAT]: 글 작성 및 AI 분석에 쓰이는 Textarea 컴포넌트 구현
  web/src/components/common/FormTextarea.tsx
Labels: ✨ Feature, 🎨 Design

#37 [REFACTOR]: import 정렬 규칙 적용
  web/src/App.tsx
  web/src/components/common/Bubble.tsx
  web/src/components/signup/AgeForm.tsx
  web/src/components/signup/GenderForm.tsx
  web/src/main.tsx
Labels: 🛠️ Refactor

#35 [FEAT]: 분석하기 페이지 UI 구현 및 Pretendard 폰트 불러오기
  web/src/assets/icons/arrow_right_bold.svg
  web/src/assets/logo/logo-cheatkey-text.svg
  web/src/components/analyze/TabSwitcher.tsx
  web/src/components/common/AppHeader.tsx
  web/src/components/common/BottomFullButton.tsx
  web/src/constants/analyzePageConstants.ts
  web/src/pages/analyze/AnalyzePage.tsx
  web/src/pages/auth/LoginPage.tsx
  web/src/pages/index.ts
  web/src/routes/AppRouter.tsx
  web/src/routes/path.ts
  web/src/styles/style.css
Labels: ✨ Feature, 🎨 Design

#42 [FEAT]: AI 분석 로딩 페이지 구현
  web/package-lock.json
  web/package.json
  web/src/assets/animation/ai_analyze_animation.json
  web/src/assets/icons/ai_banner.svg
  web/src/assets/icons/article_banner.svg
  web/src/assets/react.svg
  web/src/bridge/index.ts
  web/src/components/animation/AnalyzeLoader.tsx
  web/src/mocks/mockHomeData.ts
  web/src/pages/index.ts
  web/src/pages/loading/AnalyzeLoadingPage.tsx
  web/src/routes/AppRouter.tsx
  web/src/routes/path.ts
Labels: ✨ Feature, 🎨 Design, 🛠️ Refactor

#48 [FEAT]: 콘텐츠(아티클, 인터뷰) 페이지 UI 구현
  web/src/assets/icons/export.svg
  web/src/assets/icons/report.svg
  web/src/assets/icons/resize.svg
  web/src/assets/mock/article_mock_1.png
  web/src/assets/mock/article_mock_2.png
  web/src/assets/mock/interview_mock_1.png
  web/src/components/common/BottomNavBar.tsx
  web/src/components/common/Bubble.tsx
  web/src/components/common/CategoryTagGroup.tsx
  web/src/components/content/ContentDetailHeader.tsx
  web/src/components/content/ContentDetailMain.tsx
  web/src/components/content/ContentDetailTitle.tsx
  web/src/components/content/ContentPreview.tsx
  web/src/components/content/ContentRedirectOriginal.tsx
  web/src/constants/contentPageConstants.ts
  web/src/contexts/FontSizeContext.tsx
  web/src/hooks/useFontSize.ts
  web/src/layout/BottomLayout.tsx
  web/src/mocks/mockContentsData.ts
  web/src/pages/content/ArticleDetailPage.tsx
  web/src/pages/content/ContentListPage.tsx
  web/src/pages/content/InterviewDetatilPage.tsx
  web/src/pages/index.ts
  web/src/routes/AppRouter.tsx
  web/src/routes/path.ts
  web/src/types/content/content.types.ts
Labels: ✨ Feature, 🎨 Design

#71 [FEAT]: AI 분석 페이지 연동 및 커스텀 훅 분리, 결과지 등장 애니메이션 구현
  web/src/apis/analyze/postAnalyzeCase.ts
  web/src/apis/analyze/postAnalyzeURL.ts
  web/src/components/analyze/AnalyzeLoading.tsx
  web/src/components/analyze/ResultCardList.tsx
  web/src/constants/analyze/result/common.ts
  web/src/constants/animation/enterAnimation.ts
  web/src/constants/apiConstants.ts
  web/src/hooks/useAnalyzePage.ts
  web/src/pages/analyze/AnalyzePage.tsx
  web/src/pages/analyze/AnalyzeResultPage.tsx
  web/src/pages/index.ts
  web/src/routes/AppRouter.tsx
  web/src/routes/path.ts
  web/src/types/analyzeResult/analyzeResult.types.ts
Labels: ✨ Feature, 🎨 Design
