Repository Central-MakeUs/CheatKey-Front, pull requests merged in 2025-08, with the labels that each got.

#69 [FEAT]: 회원가입 페이지 서버 연동 및 커스텀 훅 리팩토링
  web/src/apis/auth/getAuthRegister.api.ts
  web/src/apis/auth/getCheckNickname.ts
  web/src/apis/auth/postAuthRegister.ts
  web/src/assets/animation/loading.json
  web/src/components/animation/LoadingSpinner.tsx
  web/src/components/signup/AgeForm.tsx
  web/src/components/signup/GenderForm.tsx
  web/src/components/signup/ItemForm.tsx
  web/src/components/signup/MethodForm.tsx
  web/src/components/signup/NicknameForm.tsx
  web/src/components/signup/TermForm.tsx
  web/src/constants/animation/slideAnimation.ts
  web/src/constants/apiConstants.ts
  web/src/constants/signUpConstants.ts
  web/src/hooks/useNicknameValidation.ts
  web/src/hooks/useSignUp.ts
  web/src/hooks/useSignUpTerms.ts
  web/src/pages/auth/SignUpPage.tsx
  web/src/types/signup/signup.types.ts
Labels: ✨ Feature

#78 [FEAT]: 홈 화면 api 연동
  native/apis/postReissue.ts
  web/src/apis/home/getHomeDashboard.ts
  web/src/components/home/HomeTrendingPost.tsx
  web/src/constants/apiConstants.ts
  web/src/constants/homePageConstants.ts
  web/src/mocks/mockHomeData.ts
  web/src/pages/home/Home.tsx
  web/src/types/home/home.types.ts
Labels: ✨ Feature, 🛠️ Refactor

#77 [FEAT]: 커뮤니티 게시글 상세보기 UI 구현
  web/src/assets/icons/comment_reply.svg
  web/src/components/communityDetail/CommentInput.tsx
  web/src/components/communityDetail/CommentItem.tsx
  web/src/components/communityDetail/CommentSection.tsx
  web/src/components/communityDetail/CommunityPostContent.tsx
  web/src/components/communityDetail/ImageCloseUpModal.tsx
  web/src/components/communityDetail/ReplyCommentItem.tsx
  web/src/components/communityFeed/CommunityFeedTab.tsx
  web/src/components/communityFeed/CommunityPostPreview.tsx
  web/src/components/communityWrite/PostImageUploader.tsx
  web/src/components/my/MyPostsPreview.tsx
  web/src/hooks/useCommunityWriteState.ts
  web/src/hooks/useImageCloseUp.ts
  web/src/mocks/mockCommunityDetailCommentsData.ts
  web/src/pages/communityDetail/CommunityDetail.tsx
  web/src/types/community/community.types.ts
  web/src/types/communityWrite/communityWrite.types.ts
Labels: ✨ Feature, 🎨 Design

#81 [FIX]: 커뮤니티 상세 페이지 배포 오류 수정
  web/src/pages/communityDetail/CommunityDetail.tsx
  web/src/pages/my/MyPostsPage.tsx
Labels: 🐞 Bug, 🌈 Deploy

#52 [REFACTOR]: 커뮤니티 글 작성 페이지 Toast 유효성 검사 방식 zod 기반으로 개선
  web/eslint.config.js
  web/src/hooks/useCommunityWriteState.ts
  web/src/pages/communityWrite/CommunityWrite.tsx
  web/src/schemas/communityWriteSchema.ts
Labels: 🛠️ Refactor

#83 [FIX]: 커뮤니티 작성 페이지 배포 오류 수정
  web/package-lock.json
  web/package.json
  web/src/hooks/useCommunityWriteState.ts
  web/src/schemas/communityWriteSchema.ts
Labels: 🐞 Bug, 🌈 Deploy

#84 [FEAT]: Status Bar, SafeArea 여백 스타일 적용
  native/app/_layout.tsx
  native/app/index.tsx
  web/index.html
  web/src/components/content/ContentDetailMain.tsx
  web/src/constants/homePageConstants.ts
  web/src/pages/analyze/AnalyzePage.tsx
  web/src/pages/analyze/AnalyzeResultPage.tsx
  web/src/pages/auth/LoginPage.tsx
  web/src/pages/auth/SignUpPage.tsx
  web/src/pages/content/ArticleDetailPage.tsx
  web/src/pages/content/ContentListPage.tsx
  web/src/pages/content/InterviewDetatilPage.tsx
  web/src/pages/home/Home.tsx
  web/src/styles/style.css
Labels: ✨ Feature, 🎨 Design

#86 [DESIGN]: 커뮤니티, 마이페이지 Status Bar, SafeArea 적용
  web/src/components/common/AppHeader.tsx
  web/src/pages/communityDetail/CommunityDetail.tsx
  web/src/pages/communityFeed/CommunityFeed.tsx
  web/src/pages/communityWrite/CommunityWrite.tsx
  web/src/pages/my/MyAnalysisPage.tsx
  web/src/pages/my/MyPage.tsx
  web/src/pages/my/MyPostsPage.tsx
  web/src/pages/my/TermsPage.tsx
  web/src/pages/searchPage/SearchPage.tsx
Labels: 🎨 Design

#88 [FEAT]: AI 분석 토스트 연동 및 유효성 검사 zod 변경 및 콘텐츠 공유하기 기능 추가
  native/bridge/index.ts
  web/src/assets/icons/temporary_profile_pic.png
  web/src/assets/mock/article_mock_3.png
  web/src/components/analyze/DetailResultCard.tsx
  web/src/components/common/Toast.tsx
  web/src/components/content/ContentDetailHeader.tsx
  web/src/components/home/HomeBannerList.tsx
  web/src/constants/analyze/page/analyzePageConstants.ts
  web/src/constants/analyzePageConstants.ts
  web/src/constants/homePageConstants.ts
  web/src/hooks/useAnalyzePage.ts
  web/src/hooks/useNicknameValidation.ts
  web/src/mocks/mockContentsData.ts
  web/src/pages/analyze/AnalyzePage.tsx
  web/src/pages/analyze/AnalyzeResultPage.tsx
  web/src/types/bridge/bridge.types.ts
  web/src/types/home/home.types.ts
  web/src/utils/validateNicknameFormat.ts
Labels: ✨ Feature, 🎨 Design

#93 [FEAT]: 온보딩 페이지 UI 구현 및 포탈 위치 변경
  web/index.html
  web/src/assets/onboarding/onboarding_1.png
  web/src/assets/onboarding/onboarding_2.png
  web/src/assets/onboarding/onboarding_3.png
  web/src/assets/onboarding/onboarding_4.png
  web/src/components/common/ConfirmModal.tsx
  web/src/components/common/ToTop.tsx
  web/src/components/common/Toast.tsx
  web/src/components/onboarding/OnboardingContent.tsx
  web/src/constants/onboardingConstants.ts
  web/src/pages/communityFeed/CommunityFeed.tsx
  web/src/pages/content/ArticleDetailPage.tsx
  web/src/pages/content/InterviewDetatilPage.tsx
  web/src/pages/index.ts
  web/src/pages/my/MyAnalysisPage.tsx
  web/src/pages/my/MyPostsPage.tsx
  web/src/pages/my/TermsPage.tsx
  web/src/pages/onboarding/OnboardingPage.tsx
  web/src/pages/searchPage/SearchPage.tsx
  web/src/routes/AppRouter.tsx
  web/src/routes/path.ts
Labels: ✨ Feature, 🎨 Design

#99 [FEAT]: 마이페이지 API 연동
  native/app.config.js
  native/eas.json
  native/package-lock.json
  native/package.json
  web/src/apis/auth/deleteAuthWithdraw.ts
  web/src/apis/auth/postAuthLogout.ts
  web/src/apis/my/getMypageCommunityPostsManagement.ts
  web/src/apis/my/getMypageDashboard.ts
  web/src/apis/my/getMypageDetectionHistory.ts
  web/src/components/my/AnalysisLevelBadge.tsx
  web/src/components/my/AnalysisTypeBadge.tsx
  web/src/components/my/MyAccount.tsx
  web/src/components/my/MyAnalysisList.tsx
  web/src/components/my/MyAnalysisListItem.tsx
  web/src/components/my/MyProfile.tsx
  web/src/constants/apiConstants.ts
  web/src/pages/my/MyAnalysisPage.tsx
  web/src/pages/my/MyPage.tsx
  web/src/pages/my/MyPostsPage.tsx
  web/src/store/dummy.ts
  web/src/store/useMyPostsStore.ts
  web/src/store/useMypageStore.ts
  web/src/types/my/my.types.ts
Labels: ✨ Feature, ⚙️ Chore

#102 [FEAT]: 검색 페이지 API 연동
  web/package-lock.json
  web/package.json
  web/src/apis/community/getCommunityPosts.ts
  web/src/components/common/SearchBar.tsx
  web/src/constants/apiConstants.ts
  web/src/pages/searchPage/SearchPage.tsx
Labels: ✨ Feature

#108 [FEAT]: 커뮤니티 글 작성 페이지 API 연동
  web/src/apis/community/postCommunity.ts
  web/src/apis/community/postCommunityPosts.ts
  web/src/constants/apiConstants.ts
  web/src/pages/communityWrite/CommunityWrite.tsx
  web/src/types/community/community.types.ts
Labels: ✨ Feature

#111 [FEAT]: 커뮤니티 글 작성 이미지 api 연동 수정 및 마이페이지 게시글 삭제 연동
  web/src/apis/community/deletePost.ts
  web/src/apis/community/postCommunity.ts
  web/src/apis/community/postCommunityPosts.ts
  web/src/components/my/MyPostsPreview.tsx
  web/src/constants/apiConstants.ts
  web/src/constants/commnityFeedTabs.ts
  web/src/hooks/mutations/useDeletePostMutation.ts
  web/src/pages/communityWrite/CommunityWrite.tsx
  web/src/types/community/community.types.ts
Labels: ✨ Feature

#112 [FEAT]: 커뮤니티 피드 api 연동
  web/src/pages/communityFeed/CommunityFeed.tsx
Labels: ✨ Feature

#118 [FEAT]: 플랫폼별 로그인 버튼 조건부 노출
  web/src/pages/auth/LoginPage.tsx
  web/src/utils/getPlatform.ts
Labels: ✨ Feature

#122 [STYLE]: 네비바랑 세부 수정사항 반영
  native/app/index.tsx
  web/src/components/common/BottomNavBar.tsx
  web/src/components/home/HomeTrendingPost.tsx
  web/src/components/my/MyProfile.tsx
  web/src/pages/communityWrite/CommunityWrite.tsx
  web/src/pages/home/Home.tsx
Labels: 🎨 Design

#124 [STYLE]: 커뮤니티 상세보기 내용 스타일 변경
  web/src/components/communityDetail/CommunityPostContent.tsx
Labels: 🎨 Design

#129 [FEAT]: 웹 뷰 리로드 리스너 구현
  native/app/index.tsx
  web/src/App.tsx
  web/src/hooks/useSafeAreaListener.ts
Labels: ✨ Feature

#132 [FEAT]: 안드로이드 뒤로 가기 및 네비게이션 바 임시 구현
  native/app/index.tsx
Labels: ✨ Feature

#136 [FEAT]: 아이패드 반응형 ui 구현
  web/src/components/analyze/DetailResultCard.tsx
  web/src/components/common/AppHeader.tsx
  web/src/components/common/BottomNavBar.tsx
  web/src/components/common/BottomSheet.tsx
  web/src/components/common/SearchBar.tsx
  web/src/components/communityWrite/PostImageUploader.tsx
  web/src/components/content/ContentDetailHeader.tsx
  web/src/components/content/ContentDetailTitle.tsx
  web/src/components/content/ContentPreview.tsx
  web/src/components/onboarding/OnboardingContent.tsx
  web/src/pages/communityDetail/CommunityDetail.tsx
  web/src/pages/communityWrite/CommunityWrite.tsx
  web/src/pages/content/ContentListPage.tsx
  web/src/pages/my/MyAnalysisPage.tsx
  web/src/pages/my/MyPostsPage.tsx
  web/src/pages/my/TermsPage.tsx
  web/src/pages/searchPage/SearchPage.tsx
  web/src/styles/style.css
  web/src/utils/getPlatform.ts
Labels: 🎨 Design

#139 [REFACTOR]: 필수 옵션 값 (성별, 나이) -> 선택 옵션 값으로 변경
  web/src/hooks/useSignUp.ts
  web/src/pages/auth/SignUpPage.tsx
  web/src/types/signup/signup.types.ts
Labels: 🛠️ Refactor

#142 [FEAT]: 메타 태그 적용 및 디바이스 환경에 따른 UI 표시 수정
  web/index.html
  web/src/assets/logo/logo_store_android.svg
  web/src/assets/logo/logo_store_ios.svg
  web/src/assets/meta/meta.png
  web/src/components/content/ContentDetailHeader.tsx
  web/src/components/content/ContentDetailMain.tsx
  web/src/components/content/ContentRedirectBanner.tsx
  web/src/constants/contentPageConstants.ts
  web/src/types/window.d.ts
Labels: ✨ Feature

#145 [REFACTOR]: 게시글 작성 유효성 검사 수정
  web/src/components/communityWrite/TitleForm.tsx
  web/src/schemas/communityWriteSchema.ts
Labels: 🛠️ Refactor

#147 [FIX]: 안쓰는 mock 데이터 삭제
  web/src/mocks/mockCommunityDetailCommentsData.ts
Labels: 🐞 Bug

#150 [FEAT]: 분석 불가 페이지 구현 및 회원가입 축하 모달 추가
  web/index.html
  web/package-lock.json
  web/src/assets/images/cutting_good.svg
  web/src/assets/images/result/unknown.svg
  web/src/components/analyze/ResultCardList.tsx
  web/src/components/animation/ConfettiExplosion.tsx
  web/src/components/animation/ConfettiPiece.tsx
  web/src/components/common/ConfirmModal.tsx
  web/src/components/my/MyAnalysisListItem.tsx
  web/src/constants/analyze/result/common.ts
  web/src/constants/analyze/result/detailCards.ts
  web/src/constants/analyze/result/firstCard.ts
  web/src/constants/analyze/result/index.ts
  web/src/hooks/useAnalyzePage.ts
  web/src/hooks/useSignUp.ts
  web/src/pages/analyze/AnalyzeUnknownPage.tsx
  web/src/pages/home/Home.tsx
  web/src/pages/index.ts
  web/src/routes/AppRouter.tsx
  web/src/routes/path.ts
  web/src/types/analyzeResult/analyzeResult.types.ts
Labels: ✨ Feature, 🎨 Design

#157 [FEAT]: 글 작성 이미지 유효성 검사 수정 및 세부 토스트 처리, 임시 프로필 값 수정
  web/src/assets/icons/temporary_profile_pic.svg
  web/src/assets/images/temporary_profile_pic.png
  web/src/components/communityDetail/CommentItem.tsx
  web/src/components/communityDetail/CommunityPostContent.tsx
  web/src/components/communityDetail/ReplyCommentItem.tsx
  web/src/components/communityFeed/CommunityPostPreview.tsx
  web/src/components/communityWrite/PostImageUploader.tsx
  web/src/components/my/MyPostsPreview.tsx
  web/src/constants/contentPageConstants.ts
  web/src/pages/communityWrite/CommunityWrite.tsx
  web/src/schemas/communityWriteSchema.ts
Labels: ✨ Feature

#149 [REFACTOR]: 검색페이지 및 커뮤니티 UI 개선 및 페이지 컴포넌트 리팩토링
  web/src/components/common/SearchBar.tsx
  web/src/components/communityWrite/PostBoardSelect.tsx
  web/src/pages/communityFeed/CommunityFeed.tsx
  web/src/pages/communityWrite/CommunityWrite.tsx
Labels: 🐞 Bug, 🛠️ Refactor

#160 [FEAT]: 런칭데이 피드백 반영
  web/src/components/analyze/ResultCardList.tsx
  web/src/components/communityDetail/CommunityPostContent.tsx
  web/src/components/communityDetail/ImageCloseUpModal.tsx
  web/src/components/content/ContentDetailMain.tsx
  web/src/components/home/HomeBannerList.tsx
  web/src/components/my/MyAnalysisList.tsx
  web/src/components/my/MyPostsPreview.tsx
  web/src/constants/animation/cardAnimationConstants.ts
  web/src/constants/apiConstants.ts
  web/src/constants/contentPageConstants.ts
  web/src/hooks/mutations/useDeletePostMutation.ts
  web/src/hooks/useImageCloseUp.ts
  web/src/hooks/useImageSlider.ts
  web/src/pages/analyze/AnalyzeResultPage.tsx
  web/src/pages/communityDetail/CommunityDetail.tsx
  web/src/pages/communityFeed/CommunityFeed.tsx
  web/src/pages/communityWrite/CommunityWrite.tsx
  web/src/pages/home/Home.tsx
  web/src/pages/my/MyPage.tsx
  web/src/pages/my/MyPostsPage.tsx
  치트키이용약관.txt
Labels: ✨ Feature, 🎨 Design
